---
custom_community_vmware_vmware__guest:
  networks:
  - name: "VLAN665-RD Labo" #"VLAN703-OpenShift3"
    device_type: vmxnet3
    connected: true
    start_connected: true
    label: "Network adapter 1"
  hardware:
    memory_mb: 24576
    num_cpus: 8