---
ansible_user: ansible
# # deployment_username: "{{ template_lin_username }}"
# deployment_template_password: "{{ template_lin_password }}"
# deployment_password: "{{ client_password }}"
# deployment_ssh_filename: id_rsa_okd3
# defaultvg: centos # centos for CentOS 7, rhel for RedHat 8
os_customization_for_ip: false
bastion_webroot: /home/user1/var-www-html-upi-nsx
bastion_ip: 10.255.254.23
bastion_port: 8081
bastion_container_name: webserver-upi-nsx
openshift_download_dir: /home/user1/openshift-install-4.11-upi-installer
openshift_config_dir: /home/user1/openshift-install-4.11-upi-nsx-config
openshift_example_dir: /home/user1/openshift-install-4.11-upi-nsx-examples
openshift_custom_version_source: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.11.37/openshift-install-linux.tar.gz
# https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable-4.11/openshift-install-linux.tar.gz # Leave empty if you want to target the latest stable
openshift_default_source: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-install-linux.tar.gz
openshift_default_client_source: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz
openshift_custom_ova_source: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.11/latest/rhcos-vmware.x86_64.ova
openshift_cluster_name: openshift-upi-nsx
openshift_cluster_domain: rdlabo.local
openshift_networkType: ncp
openshift_clusterNetworks:
- cidr: 10.128.0.0/14 # Default: 10.128.0.0/14
  hostPrefix: 23 # Default: 23
openshift_machineNetwork_cidr:
- cidr: 10.200.0.0/24 # Default: 10.0.0.0/16
# openshift_machineNetwork_cidr: 172.16.0.0/16 # Default: 10.0.0.0/16
openshift_serviceNetwork:
- 172.30.0.0/16  # Default: 172.30.0.0/16, only single network allowed
openshift_api_url: "api.openshift-upi-nsx.rdlabo.local"
openshift_api_int_url: "api-int.openshift-upi-nsx.rdlabo.local"
openshift_api_ip: 10.200.0.1 # From Managament segment
openshift_api_port: 6443
openshift_api_ignition_port: 22623
openshift_api_vlan: NSX-OpenShift-UPI-NSX #VLAN665-RD Labo
openshift_ingress_url: "*.apps.openshift-upi-nsx.rdlabo.local"
openshift_ingress_ip: 10.200.1.1 # First IP from IP Pool for External LBs
openshift_ingress_vlan: NSX-OpenShift-UPI-NSX #VLAN665-RD Labo
# You can find your own auth code on https://console.redhat.com/openshift/install/vsphere, the pull secret, then prepend every '"' with '\'
openshift_auth_code: "{\"auths\":{\"cloud.openshift.com\":{\"auth\":\"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNTZmZjFkYTg2ZWMyNDlkOGExNWY0NDQ0YmZlNmYyZjA6UUVOMk9DWlBVUEdRMEwzVU5VNEtTVlRCMTYwV1pKWDBCOTdFT1RRWUJUMkVEWVA2OFoyUU1MMVJYQjQ3UUE2Vw==\",\"email\":\"thomas.biesmans@realdolmen.com\"},\"quay.io\":{\"auth\":\"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNTZmZjFkYTg2ZWMyNDlkOGExNWY0NDQ0YmZlNmYyZjA6UUVOMk9DWlBVUEdRMEwzVU5VNEtTVlRCMTYwV1pKWDBCOTdFT1RRWUJUMkVEWVA2OFoyUU1MMVJYQjQ3UUE2Vw==\",\"email\":\"thomas.biesmans@realdolmen.com\"},\"registry.connect.redhat.com\":{\"auth\":\"fHVoYy1wb29sLWU3YjIxY2E2LWMzNGEtNDAxNS05NzQ2LWE1MjgzMGU1MDVhYTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBZVEF5WldJMU4yVXdOemswTURCalltVmtPREF6TTJWaVlUaG1NVEUxTlNKOS5OOGxBMVQzSGNXWERfS3lXNzljeUZJZV9Fc3NJSzh5cTRxUE9MMjMycVIwSmlycXVFd1ZLRm10N2NhdnQ4N3padVA3V2taTXdHeUE0T2FfV1pwQkdtOXk5Zm9pMWo2UmlvV0JhNC03MkdHY0FtSmpKeVM3bjNMRWxxR1U1ZmFIVDZrc05lQTkxQXMtSE5UZmpzaktycUd6NUthV2J0QlZPR1VROW1pOFFJWkEtQ2c4MWo3Q2ttOF9kTXJkR2N3NnlpOXJ2YkxCR3hxbENIa19pN3h4aWRMQ1hzbjdSWVdWUjZrTmEtR21haGpBMzdJTU52RFJZcW0yYWpUYXhwakpUWlhCM21jeWNpMnRBQVhOV05tampQaVJYRmVzY1l2dFZkbVZtWlF1cjFXajNfcHVLU3JBeS1OUjVfZlcxVm9EVHkyYTRFQUlwQmxMU1JpbFlLZ2ktTUR4czlfMl9lZGE5ak9pUkJzVTF1Snd5RUU0bm9mT3NBZUlyNnBCeWdhaDNkZjhrTC15cGVGeE4xOE5oVFI0YmFjLTJnbVVGS3NYdVBjUGRmR0hxNFQyYUM5SFQxYlg0TDJaOTNpcFRXUmVqZ2MwOWVKM3NORGdXZDJvZ3NCb2o5b0dYemlSR3hxZjQ1dUNONmNQNXJkMFR1V0ltdVJzNUlLTmxJak5NbDd4QUhpUVRtMXllbjEyZkx1N1BJYTc2Ul9mQ1dyMkw5S0xBbmFGR21LbldyR3Q2a3dSQ1hROEVEWHNfME9oT3lyMDJlUXY5VHVLb3BxRXBOa3lLcm1VWFprSjFMQnI1N1dmZmlhVDY5aWZibzNJS3NvcTZOMFU2Y0E2LUF3THpBQTN4aDU2UGlrWF9mb1laRExlUDJNeUtfYjduNzNJZW1Zd19tTDhCSWRHUmFwNA==\",\"email\":\"thomas.biesmans@realdolmen.com\"},\"registry.redhat.io\":{\"auth\":\"fHVoYy1wb29sLWU3YjIxY2E2LWMzNGEtNDAxNS05NzQ2LWE1MjgzMGU1MDVhYTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBZVEF5WldJMU4yVXdOemswTURCalltVmtPREF6TTJWaVlUaG1NVEUxTlNKOS5OOGxBMVQzSGNXWERfS3lXNzljeUZJZV9Fc3NJSzh5cTRxUE9MMjMycVIwSmlycXVFd1ZLRm10N2NhdnQ4N3padVA3V2taTXdHeUE0T2FfV1pwQkdtOXk5Zm9pMWo2UmlvV0JhNC03MkdHY0FtSmpKeVM3bjNMRWxxR1U1ZmFIVDZrc05lQTkxQXMtSE5UZmpzaktycUd6NUthV2J0QlZPR1VROW1pOFFJWkEtQ2c4MWo3Q2ttOF9kTXJkR2N3NnlpOXJ2YkxCR3hxbENIa19pN3h4aWRMQ1hzbjdSWVdWUjZrTmEtR21haGpBMzdJTU52RFJZcW0yYWpUYXhwakpUWlhCM21jeWNpMnRBQVhOV05tampQaVJYRmVzY1l2dFZkbVZtWlF1cjFXajNfcHVLU3JBeS1OUjVfZlcxVm9EVHkyYTRFQUlwQmxMU1JpbFlLZ2ktTUR4czlfMl9lZGE5ak9pUkJzVTF1Snd5RUU0bm9mT3NBZUlyNnBCeWdhaDNkZjhrTC15cGVGeE4xOE5oVFI0YmFjLTJnbVVGS3NYdVBjUGRmR0hxNFQyYUM5SFQxYlg0TDJaOTNpcFRXUmVqZ2MwOWVKM3NORGdXZDJvZ3NCb2o5b0dYemlSR3hxZjQ1dUNONmNQNXJkMFR1V0ltdVJzNUlLTmxJak5NbDd4QUhpUVRtMXllbjEyZkx1N1BJYTc2Ul9mQ1dyMkw5S0xBbmFGR21LbldyR3Q2a3dSQ1hROEVEWHNfME9oT3lyMDJlUXY5VHVLb3BxRXBOa3lLcm1VWFprSjFMQnI1N1dmZmlhVDY5aWZibzNJS3NvcTZOMFU2Y0E2LUF3THpBQTN4aDU2UGlrWF9mb1laRExlUDJNeUtfYjduNzNJZW1Zd19tTDhCSWRHUmFwNA==\",\"email\":\"thomas.biesmans@realdolmen.com\"}}}"
deployment_ssh_filename: id_rsa_openshift4
citrix_lb_integration: false
nsx_integration: true

default_community_vmware_vmware__guest:
  datacenter: P250
  cluster: RDLabo-NSX
  folder: /P250/vm/RD Labo/Various/OpenShift-4-UPI-NSX
  name: {} # set later"{{ hostvars[item]['inventory_hostname'] }}"
  state: poweredoff
  template: Template-RHCOS-UPI-NSX # Case sensitive
  template_type: eagerZeroedThick # thin, thick, eagerZeroedThick
  disk:
  - size_gb: 120
    type: eagerzeroedthick # thin, thick, eagerzeroedthick
    datastore: RDL3PAR01_ESXCORE_VMFS_L102
  # Add another disk from an existing VMDK
  #- filename: "[datastore1] testvms/testvm_2_1/testvm_2_1.vmdk"
  hardware:
    memory_mb: 16384
    num_cpus: 4
    num_cpu_cores_per_socket: 2
    scsi: paravirtual
    # memory_reservation_lock: true
    # mem_limit: 8096
    # mem_reservation: 4096
    # cpu_limit: 8096
    # cpu_reservation: 4096
    max_connections: 5
    # hotadd_cpu: True
    # hotremove_cpu: True
    # hotadd_memory: False
    version: 19 # Hardware version of virtual machine, already up-to-date
    boot_firmware: "efi"
  # cdrom:
  #     - controller_number: 0
  #       unit_number: 0
  #       state: present
  #       type: iso
  #       iso_path: "[datastore1] livecd.iso"
  networks:
  - name: "NSX-OpenShift-UPI-NSX"
    device_type: vmxnet3
    connected: true
    start_connected: true
    label: "Network adapter 1"
    # type: static # Used for the IP and for O/S customization
    # ip: {} # Set through inventory, used for O/S customization
    # gateway: 10.255.254.254 # Used for O/S customization
    # netmask: 255.255.255.0 # Used for O/S customization
    # mac: aa:bb:dd:aa:00:14
  # customization:
  #   dns_servers: "{{ dns_servers }}" # definition on networks is only for Windows
  #   domain: "{{ dns_domain }}" # definition on networks is only for Windows
  wait_for_ip_address: false
  advanced_settings: # Use '{}' or uncomment any of the lower options
    - key: disk.EnableUUID
      value: true
    - key: ethernet0.checkMACAddress
      value: false
    - key: ethernet1.checkMACAddress
      value: false
    - key: guestinfo.ignition.config.data.encoding
      value: base64
    - key: guestinfo.ignition.config.data
      value: 'TBD'
ncp_config:
  ncp_plugin_source: https://github.com/vmware/nsx-container-plugin-operator/releases/download/v4.1.0/openshift4.tar.gz
  baseline_policy_type: allow_namespace
  enable_multus: true # False by default, true for Multus with multi-NIC support
  ncp_image: vmware/nsx-container-plugin-operator:v4.1.0
  certificate_nsx_client_name: nsx-admin-cert
  certificate_nsx_client_subject: "/CN=nsx-admin-ansible"
  single_tier_topology: True # Single-tier = no T1, False not supported on OpenShift
  top_tier_gateway: T1-GW #2e6ed5ea-068b-4066-9b58-01187f522a73 #TO-GW's SR through get logical-router
  overlay_tz: dbe81977-95d6-499d-9bf4-a1c7d5d5c8b3 # NSX-Overlay
  edge_cluster: 7a4b9a26-ec5a-44d4-ac8f-9f5fe5f660ef # EdgeCluster01
  external_ip_pools_lb: openshift-upi-nsx-external-lb-pool
  external_ip_pools: openshift-upi-nsx-ip-pool
  ncp_operator_version: "vmware/nsx-container-plugin-operator:v4.1.0" # See https://hub.docker.com/r/vmware/nsx-container-plugin-operator/tags
  # The container plugin operator is publicly available, the container plugin itself isn't, so download it to the download dir.
  # See https://customerconnect.vmware.com/downloads/info/slug/networking_security/vmware_nsx/4_x#drivers_tools
  # List of versions:
  # - version: v4.0.0
  #   ncp_image_downloaded_container_file: "nsx-container-4.0.0.20092570.zip" 
  #   ncp_image_extracted_container_file: "nsx-container-4.0.0.20092570/Kubernetes/nsx-ncp-ubi-4.0.0.20092570.tar"
  #   ncp_image_loaded_image_name: "registry.local/4.0.0.20092570/nsx-ncp-ubi:latest"
  #   ncp_image_tagged_image_name_for_openshift: "nsx-ncp-ubi:v4.0.0"
  # - version: v4.0.1
  #   ncp_image_downloaded_container_file: "nsx-container-4.0.1.20665035.zip" 
  #   ncp_image_extracted_container_file: "nsx-container-4.0.1.20665035/Kubernetes/nsx-ncp-ubi-4.0.1.20665035.tar"
  #   ncp_image_loaded_image_name: "registry.local/4.0.1.20665035/nsx-ncp-ubi:latest"
  #   ncp_image_tagged_image_name_for_openshift: "nsx-ncp-ubi:v4.0.1"
  # - version: v4.1.0
  #   ncp_image_downloaded_container_file: "nsx-container-4.1.0.21302845.zip" 
  #   ncp_image_extracted_container_file: "nsx-container-4.1.0.21302845/Kubernetes/nsx-ncp-ubi-4.1.0.21302845.tar"
  #   ncp_image_loaded_image_name: "registry.local/4.0.1.21302845/nsx-ncp-ubi:latest"
  #   ncp_image_tagged_image_name_for_openshift: "nsx-ncp-ubi:v4.1.0"
  ncp_image_downloaded_container_file: "nsx-container-4.1.0.21302845.zip" 
  ncp_image_extracted_container_file: "nsx-container-4.1.0.21302845/Kubernetes/nsx-ncp-ubi-4.1.0.21302845.tar"
  ncp_image_loaded_image_name: "registry.local/4.1.0.21302845/nsx-ncp-ubi:latest"
  ncp_image_tagged_image_name_for_openshift: "nsx-ncp-ubi:v4.1.0"
  root_ca_certificate_name: root-ca
  root_ca_certificate_subject: "/C=BE/ST=Vlaams-Brabant/L=Huizingen/O=RDLabo/OU=IT/CN=Root CA RDLabo"
  bastion_image_registry_port: 8082
  bastion_image_registry_container_name: registry-upi-nsx
  bastion_image_registry_volume: /home/user1/var-image-registry
  bastion_image_registry_certificate_volume: /home/user1/var-image-registry-certs
  bastion_image_registry_certificate_name: image-registry-cert
  bastion_image_registry_certificate_subject: "/CN=Image Registry for NCP"
  bastion_image_registry_certificate_subject_rev: "countryName = BE\nstateOrProvinceName = Vlaams-Brabant\nlocalityName = Huizingen\norganizationName = RDLabo\ncommonName = Image Registry for NCP"
  openshift_tls_certificate_name: openshift-tls-cert
  openshift_tls_certificate_subject: "/C=BE/ST=Vlaams-Brabant/L=Huizingen/O=RDLabo/OU=IT/CN=*.apps.openshift-upi-nsx.rdlabo.local"
  openshift_tls_certificate_subject_rev: "countryName = BE\nstateOrProvinceName = Vlaams-Brabant\nlocalityName = Huizingen\norganizationName = RDLabo\ncommonName = *.apps.openshift-upi-nsx.rdlabo.local"
  openshift_tls_certificate_san_dns: "*.apps.openshift-upi-nsx.rdlabo.local"

ipam_config:
  nic2_dhcp:
    network_nic: ens224
    network_ipam:
      type: dhcp
  nic2_whereabouts:
    network_nic: ens224
    network_ipam:
      type: whereabouts
      range: 10.10.0.0/24
      exclude:
      - 10.10.0.0/25

openshift_data_foundation_config:
  operator_name: odf-operator # Found through oc get packagemanifests -n openshift-marketplace | grep odf
  operator_channel: stable-4.11 # Found through oc get packagemanifests/odf-operator -n openshift-marketplace -o yaml | grep stable
  operator_automatic_install_plan_approval: true
  operator_manage_namespaces: openshift-storage
  operator_subscription_source: redhat-operators
  operator_catalogsource_setup: false
  operator_catalogsource_name: redhat-operators-snapshot-odf
  operator_catalogsource_image: ""
  operator_catalogsource_image_tag: ""
  storage_system_name: ocs-deviceset-thin-1
  osd_requests_cpu: 1 # Default 1
  osd_requests_memory: 5Gi # Default 5Gi
  osd_limits_cpu: 2 # Default 2
  osd_limits_memory: 5Gi # Default 5Gi
  osd_requests_storage: 512Gi # Minimum 512Gi
  osd_storageclassname: thin # Default thin for VMware
  mds_requests_cpu: 1 # Default 1
  mds_requests_memory: 8Gi # Default 8Gi
  mds_limits_cpu: 3 # Default 3
  mds_limits_memory: 8Gi # Default 8Gi
  rgw_requests_cpu: 1 # Default 1
  rgw_requests_memory: 4Gi # Default 4Gi
  rgw_limits_cpu: 2 # Default 2
  rgw_limits_memory: 4Gi # Default 4Gi

commvault_config:
  sa_name: sa-commvault
  sa_namespace: default
  sa_clusterrolebinding_name: default-backup-cluster-admin