---
ansible_user: ansible
# deployment_username: "{{ template_lin_username }}"
deployment_template_password: "{{ template_lin_password }}"
deployment_password: "{{ client_password }}"
deployment_ssh_filename: id_rsa_okd3
defaultvg: centos # centos for CentOS 7, rhel for RedHat 8
os_customization_for_ip: true
default_community_vmware_vmware__guest:
  datacenter: P250
  cluster: RDLabo
  folder: /RD Labo/Various/OpenShift-OKD 3.11
  name: {} # set later"{{ hostvars[item]['inventory_hostname'] }}"
  state: poweredon
  template: TemplCentOS7.9 # Case sensitive
  disk:
  - size_gb: 40
    type: eagerzeroedthick # thin, thick, eagerzeroedthick
    datastore: RDL3PAR01_ESXCORE_VMFS_L101
  - size_gb: 45
    type: eagerzeroedthick # thin, thick, eagerzeroedthick
    datastore: RDL3PAR01_ESXCORE_VMFS_L101
  # Add another disk from an existing VMDK
  #- filename: "[datastore1] testvms/testvm_2_1/testvm_2_1.vmdk"
  hardware:
    memory_mb: 8192
    num_cpus: 4
    num_cpu_cores_per_socket: 2
    scsi: paravirtual
    # memory_reservation_lock: true
    # mem_limit: 8096
    # mem_reservation: 4096
    # cpu_limit: 8096
    # cpu_reservation: 4096
    max_connections: 5
    # hotadd_cpu: True
    # hotremove_cpu: True
    # hotadd_memory: False
    version: 14 # Hardware version of virtual machine
    boot_firmware: "efi"
  # cdrom:
  #     - controller_number: 0
  #       unit_number: 0
  #       state: present
  #       type: iso
  #       iso_path: "[datastore1] livecd.iso"
  networks:
  - name: VLAN665-RD Labo
    device_type: vmxnet3
    connected: true
    start_connected: true
    type: static
    ip: {} # Set through inventory
    gateway: 10.255.254.254 # move to network yml
    netmask: 255.255.255.0
    #mac: aa:bb:dd:aa:00:14
  customization:
    dns_servers: "{{ dns_servers }}" # definition on networks is only for Windows
    domain: "{{ dns_domain }}" # definition on networks is only for Windows
  wait_for_ip_address: true