---
vcenter_hostname: rdlvc11a.rdlabo.local
vcenter_username: "{{ vmware_sa_username }}"
vcenter_password: "{{ vmware_sa_password }}"
parallel_deployments: 2
delete_during_retry: true
default_vmware_portgroup:
- name: "VLAN665-RD Labo"
  device_type: vmxnet3
  connected: true
  start_connected: true
  # type: dynamic
nsx_hostname: 10.255.254.127
nsx_username: "{{ vmware_nsx_username }}"
nsx_password: "{{ vmware_nsx_password }}"
nsx_segment_config:
- name: NSX-OpenShift-UPI-NSX
  transport_zone_display_name: "NSX-Overlay"
  subnets:
  - gateway_address: 10.200.0.254/24
  connectivity_path: /infra/tier-1s/T1-GW
  dhcp_config_path: /infra/dhcp-relay-configs/RDLDC02
- name: NSX-OpenShift-ClientSubnet
  transport_zone_display_name: "NSX-Overlay"
  subnets:
  - gateway_address: 10.10.0.254/24
  connectivity_path: /infra/tier-1s/T1-GW
  dhcp_config_path: /infra/dhcp-relay-configs/RDLDC02



