---
vcenter_hostname: rdlvc11a.rdlabo.local
vcenter_username: "{{ vmware_sa_username }}"
vcenter_password: "{{ vmware_sa_password }}"
parallel_deployments: 2
delete_during_retry: true
default_vmware_portgroup:
- name: "VLAN665-RD Labo"
  device_type: vmxnet3
  connected: true
  start_connected: true
  # type: dynamic