--- 
- import_playbook: tasks/check_all.yml

- name: Deploy VMs
  hosts: rhel_vms
  gather_facts: false
  vars_files:
  - passwords/ansible_vault.yml
  - vars/network-config.yml
  tasks:

  - name: Combine customized VM config
    set_fact:
      community_vmware_vmware__guest: "{{ default_community_vmware_vmware__guest | combine(custom_community_vmware_vmware__guest, recursive=true) }}"
      ansible_becomes_password: "{{ client_password }}"
    tags: always

  - name: Ensure Ansible become password is set
    set_fact:
      ansible_become_password: "{{ deployment_password }}"
    when: ansible_become_password is undefined or ansible_become_password != deployment_password
    tags: always

  # - name: biep
  #   debug:
  #     msg: "{{ vars.community_vmware_vmware__guest }}"

  - name: Deploy DNS records
    vars:
      target_group_dns: "{{ ansible_play_hosts }}" #"{{ groups.rhel_vms }}"
    ansible.builtin.import_tasks: tasks/deploy-windows-dns-records-old.yml

  - name: Deploy VMs
    ansible.builtin.include_tasks: tasks/deploy-vmware-vms-from-template.yml

  - name: Check whether new SSH key is already created
    ansible.builtin.include_tasks: tasks/check_local_ssh_key_creation.yml
    run_once: true

  - name: Import VM's SSH key to prevent acceptance question
    ansible.builtin.include_tasks: tasks/import-host-ssh-key.yml

  - name: Deploy SSH key on VMs
    ansible.builtin.include_tasks:
      file: tasks/deploy-ssh-key-authentication.yml
    #   apply:
    #     tags: current
    # tags: current

  - name: Ensure that cloud-init does not prevent network configuration persistence
    ansible.builtin.include_tasks: tasks/deploy-vmware-vms-persist-networking.yml
    
  - name: Grow the templates disk to their maximum size
    ansible.builtin.include_tasks:
      file: tasks/extend-vm-disks.yml
      apply:
        tags: storage_extend
    tags: storage_extend


- name: Configure VMs
  hosts: rhel_vms
  gather_facts: true
  vars_files:
  - passwords/ansible_vault.yml
  - vars/network-config.yml
  tasks:

  - name: Configure yum for epel, no dvd
    ansible.builtin.include_tasks:
      file: tasks/configure-yum-epel.yml
      apply:
        tags: yum
    tags: yum

  - name: test Yum
    yum:
      name:
        open-vm-tools
      state: present
    become: yes
    tags: yum

  - name: Deploy additional OpenShift 3.11 pre-reqs
    ansible.builtin.include_tasks:
      file: tasks/deploy-openshift-3-prereqs.yml
      apply:
        tags: okd
    tags: okd
    


    