
- name: Deploy OpenShift authentication
  hosts: openshift_bootstrap_nodes
  gather_facts: false
  vars_files:
  - passwords/ansible_vault.yml
  - vars/network-config.yml
  - group_vars/vcenter_vms.yml
  environment:
    KUBECONFIG: "{{ vars.openshift_config_dir }}/auth/kubeconfig"
  tasks:

  - name: Deploy Azure AD
    tags: deploy_azure_ad
    delegate_to: localhost
    block:

    - name: Deploy OAuth IdentityProvider for Azure AD
      block:

      - name: Add OpenID secret as literal
        vars:
          app_namespace: "{{ item.app_namespace }}"
          app_secret_name: "{{ item.app_secret_name }}"
          app_secret_literals: "{{ item.app_secret_literals }}"
        kubernetes.core.k8s:
          state: present
          template: 'templates/openshift_4_resource_secret_literal.yml'
        with_items: "{{ authentication_authorization_config.identity_providers }}"
        loop_control:
          label: "{{ item.app_secret_name }}"
          
      - name: Add Identity Provider(s)
        kubernetes.core.k8s:
          state: present
          template: 'templates/openshift_4_resource_identityprovider_oauth_AAD.yml'
          