---

- hosts: aruba_switches
  collections:
  - arubanetworks.aos_switch
  vars_files:
  - passwords/ansible_vault.yml
  - vars/network-config.yml
  vars:
    ansible_connection: network_cli
    ansible_ssh_private_key_file: /home/user1/.ssh/id_rsa_ansibledeployment # Otherwise an error is thrown
  tasks:

  - name: Deploy VLANs on Aruba switches
    tags: deploy_lan
    block:

    - name: Deploy VLANs on Aruba switches
      ansible.builtin.include_tasks:
        file: tasks/deploy-aruba-vlans.yml
        apply:
          tags: deploy_lan
      tags: deploy_lan


- hosts: fortigate_appliances
  collections:
  - fortinet.fortios
  vars_files:
  - passwords/ansible_vault.yml
  - vars/network-config.yml
  # connection: httpapi
  tasks:      

  - name: Deploy VLANs on FortiGate L3 appliances
    ansible.builtin.include_tasks:
      file: tasks/deploy-fortigate-vlans.yml
      apply:
        tags: deploy_fortigate
    tags: deploy_fortigate
        

- hosts: virtual_connect
  vars_files:
  - passwords/ansible_vault.yml
  - vars/network-config.yml
  vars:
    ansible_connection: network_cli
    ansible_ssh_private_key_file: /home/user1/.ssh/id_rsa_ansibledeployment # Otherwise an error is thrown
  tasks:

  - name: Deploy VLANs on Virtual Connect
    tags: deploy_vc
    block:

    - name: Deploy VLANs on Virtual Connect
      ansible.builtin.include_tasks:
        file: tasks/deploy-virtualconnect-vlans.yml
        apply:
          tags: deploy_vc
      tags: deploy_vc


      
    # - name: Deploy NSX segments
    #   ansible.builtin.include_tasks:
    #     file: tasks/deploy-vmware-nsx-segments.yml
    #     apply:
    #       tags: vm
    #   tags: vm, deploy_nsx_segments
    #   when: nsx_integration