
- name: Deploy OpenShift authentication
  hosts: openshift_bootstrap_nodes
  gather_facts: false
  vars_files:
  - passwords/ansible_vault.yml
  - vars/network-config.yml
  - group_vars/vcenter_vms.yml
  environment:
    KUBECONFIG: "{{ vars.openshift_config_dir }}/auth/kubeconfig"
  tasks:

  - name: Deploy Azure AD
    tags: deploy_azure_ad
    delegate_to: localhost
    block:

    - name: Deploy OAuth IdentityProvider for Azure AD
      block:

      - name: Add OpenID secret as literal
        vars:
          app_namespace: "{{ item.app_namespace }}"
          app_secret_name: "{{ item.app_secret_name }}"
          app_secret_literals: "{{ item.app_secret_literals }}"
        kubernetes.core.k8s:
          state: present
          template: 'templates/openshift_4_resource_secret_literal.yml'
        with_items: "{{ authentication_authorization_config.identity_providers }}"
        loop_control:
          label: "{{ item.app_secret_name }}"
          
      - name: Add Identity Provider(s)
        kubernetes.core.k8s:
          state: present
          template: 'templates/openshift_4_resource_identityprovider_oauth_AAD.yml'
      
      - name: Add cluster admin Cluster Role Binding for our OpenID groups
        vars:
          crb_name: "{{ item.crb_name }}"
          role_apigroup: rbac.authorization.k8s.io
          role_name: cluster-admin
          role_kind: ClusterRole
          subject_name: "{{ item.group_name }}"
          subject_kind: Group
        kubernetes.core.k8s:
          api_version: apps/v1
          template: 'templates/openshift_4_resource_clusterrolebinding.yml'
        with_items: "{{ authentication_authorization_config.cluster_admins }}"

      - name: Disable self-provisioning for any authenticated user
        vars:
          crb_name: self-provisioners
          role_apigroup: rbac.authorization.k8s.io
          role_name: self-provisioner
          role_kind: ClusterRole
          subject_name: system:authenticated:oauth
          subject_kind: Group
        kubernetes.core.k8s:
          api_version: apps/v1
          state: absent
          template: 'templates/openshift_4_resource_clusterrolebinding.yml'
        when: not authentication_authorization_config.self_provisioning_for_any_authenticated_user

      - name: Add self-provisioner Cluster Role Binding for our OpenID groups
        vars:
          crb_name: "{{ item.crb_name }}"
          role_apigroup: rbac.authorization.k8s.io
          role_name: self-provisioner
          role_kind: ClusterRole
          subject_name: "{{ item.group_name }}"
          subject_kind: Group
        kubernetes.core.k8s:
          api_version: apps/v1
          template: 'templates/openshift_4_resource_clusterrolebinding.yml'
        with_items: "{{ authentication_authorization_config.self_provisioners }}"