---
- name: Deploy the 'Kyverno' policy engine on OpenShift
  hosts: openshift_bootstrap_nodes
  gather_facts: false
  vars_files:
  - passwords/ansible_vault.yml
  - vars/network-config.yml
  - group_vars/vcenter_vms.yml
  environment:
    KUBECONFIG: "{{ vars.openshift_config_dir }}/auth/kubeconfig"
  tasks:

  - name: Deploy Kyverno
    tags: deploy_kyverno
    delegate_to: localhost
    block:

    - name: Install helm if not exists
      unarchive:
        src: "{{ kyverno_config.helm_version_url }}"
        dest: ~/bin
        extra_opts: "--strip-components=1"
        # owner: root
        # group: root
        # mode: 0755
        remote_src: true
      args:
        creates: /usr/local/bin/helm
      run_once: yes

    - name: Add Kyverno Helm repository
      kubernetes.core.helm_repository:
        name: kyverno
        repo_url: https://kyverno.github.io/kyverno/
        force_update: no

    - name: Install the Kyverno Helm chart
      kubernetes.core.helm:
        name: kyverno
        chart_ref: kyverno/kyverno
        chart_version: "{{ kyverno_config.kyverno_version }}"
        release_namespace: "{{ kyverno_config.kyverno_namespace }}"
        create_namespace: yes
        values:
          admissionController:
            replicas: 3
          backgroundController:
            replicas: 2
          cleanupController:
            replicas: 2
          reportsController:
            replicas: 2

  - name: Deploy Kyverno policies
    tags: deploy_kyverno_policies
    delegate_to: localhost
    block:

    # - name: Enforce labels in customer deployments
    #   kubernetes.core.k8s:
    #     state: present
    #     definition:
    #       apiVersion: kyverno.io/v1
    #       kind: ClusterPolicy
    #       metadata:
    #         name: enforce-deployments-label-for-idp-users
    #       spec:
    #         validationFailureAction: Enforce
    #         background: false
    #         rules:
    #         - name: check-labels-for-idp-users
    #           match:
    #             any:
    #             - resources:
    #                 kinds:
    #                 - "*"
    #                 operations:
    #                 - CREATE
    #                 - UPDATE
    #               subjects:
    #               - kind: Group
    #                 name: "{{ authentication_authorization_config.self_provisioners[0].group_name }}"
    #           validate:
    #             message: "The label 'customer' is required for deployments."
    #             pattern:
    #               metadata:
    #                 labels:
    #                   customer: "?*"
    #                    - name: Enforce labels in customer deployments

    - name: Enforce labels in customer deployments
      vars:
        new_rule_all_resources:
          name: "check-labels-for-idp-users-{{ group.group_customer_label }}"
          match:
            any:
            - resources:
                kinds:
                - Deployment
                - DeploymentConfig
                - StatefulSet
                - Service
                - Route
                - Namespace
                - Secret
                - ConfigMap
                - PersistentVolume
                - PersistentVolumeClaim
                - BuildConfig
                - ImageStream
                operations:
                - CREATE
                - UPDATE
              subjects:
              - kind: Group
                name: "{{ group.group_name }}"
          mutate:
            patchStrategicMerge:
                  metadata:
                    labels:
                      customer: "{{ group.group_customer_label }}"
        new_rule_deployment_resources:
          name: "check-deployment-labels-and-nodeSelector-for-idp-users-{{ group.group_customer_label }}"
          match:
            any:
            - resources:
                kinds:
                - Deployment
                - DeploymentConfig
                operations:
                - CREATE
                - UPDATE
              subjects:
              - kind: Group
                name: "{{ group.group_name }}"
          mutate:
            patchStrategicMerge:
              spec:
                template:
                  metadata:
                    labels:
                      customer: "{{ group.group_customer_label }}"
                  spec:
                    nodeSelector:
                      dedicated-node: "{{ group.group_dedicated_node_label | default('Shared') }}"
      set_fact:
        rules: "{{ rules | default([]) + [new_rule_all_resources] + [new_rule_deployment_resources] }}"
      with_items: "{{ authentication_authorization_config.self_provisioners }}"
      loop_control:
        loop_var: group
        label: "{{ group.group_name_description_only }}"

    - name: Enforce labels in customer deployments
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: kyverno.io/v1
          kind: ClusterPolicy
          metadata:
            name: add-customer-labels-for-idp-users
          spec:
            validationFailureAction: Enforce
            background: false
            rules: "{{ rules }}"
