--- 
- import_playbook: check_all.yml

# - name: Deploy DNS records
#   hosts: windows_dns
#   vars_files:
#   - passwords/ansible_vault.yml
#   - vars/network-config.yml
#   tasks:

#   - name: Deploy DNS records
#     vars:
#       target_group_dns: "{{ groups.rhel8_vms }}"
#     ansible.builtin.include_tasks: tasks/deploy-windows-dns-records.yml


- name: Deploy VMs
  hosts: rdlokd3mstr01.rdlabo.local # rhel8_vms # 
  gather_facts: false
  vars_files:
  - passwords/ansible_vault.yml
  - vars/network-config.yml
  tasks:

  - name: Combine customized VM config
    set_fact:
      community_vmware_vmware__guest: "{{ default_community_vmware_vmware__guest | combine(custom_community_vmware_vmware__guest, recursive=true) }}"

  # - name: biep
  #   debug:
  #     msg: "{{ vars.community_vmware_vmware__guest }}"

  - name: Deploy DNS records
    vars:
      target_group_dns: "{{ ansible_play_hosts }}" #"{{ groups.rhel8_vms }}"
    ansible.builtin.include_tasks: tasks/deploy-windows-dns-records.yml

  - name: Deploy VMs
    ansible.builtin.include_tasks: tasks/deploy-vmware-vms-from-template.yml

  - name: Import VM's SSH key to prevent acceptance question
    ansible.builtin.include_tasks: tasks/import-host-ssh-key.yml

  - name: Deploy SSH key on VMs
    ansible.builtin.include_tasks: tasks/deploy-ssh-key-authentication.yml

  - name: Grow the templates disk to their maximum size
    ansible.builtin.include_tasks: tasks/extend-vm-disks.yml

  - name: Check alive
    debug:
      msg: 'Biep from host!'
  




  - name: test
    yum:
      name:
        open-vm-tools
      state: present
  - name: halt
    fail: {}

  
  
  # - name: Biep list detail
  #   ansible.builtin.debug:
  #     msg: "{{ item.community.vmware.vmware_guest.state }}"
  #   when: hostvars[item]['inventory_hostname'] == 'rdlokd3infr02.rdlabo.local'
  #   loop: "{{ rhel8_vms }}"

# - name: Configure VMs
#   hosts: vcenter_vms
#   gather_facts: false

#   tasks:
#   - name: Biep
#     ansible.builtin.debug:
#       msg: "{{ item }}"
#     loop: "{{ rhel8_vms }}"


- name: Tasks
  hosts: localhost 
  connection: local 
  gather_facts: false 

  tasks:
  - name: Biep
    ansible.builtin.debug:
      msg: "biep" 
