---

- hosts: aruba_switches
  collections:
  - arubanetworks.aos_switch
  vars_files:
  - passwords/ansible_vault.yml
  - vars/network-config.yml
  vars:
    ansible_connection: network_cli
    ansible_ssh_private_key_file: /home/user1/.ssh/id_rsa_ansibledeployment # Otherwise an error is thrown
  tasks:

  - name: Deploy VLANs on Aruba switches
    tags: deploy_lan
    block:

    - name: Deploy VLANs on Aruba switches
      ansible.builtin.include_tasks:
        file: tasks/deploy-aruba-vlans.yml
        apply:
          tags: deploy_lan
      tags: deploy_lan


- hosts: fortigate_appliances
  collections:
  - fortinet.fortios
  vars_files:
  - passwords/ansible_vault.yml
  - vars/network-config.yml
  # connection: httpapi
  tasks:      

  - name: Deploy VLANs on FortiGate L3 appliances
    ansible.builtin.include_tasks:
      file: tasks/deploy-fortigate-vlans.yml
      apply:
        tags: deploy_fortigate
    tags: deploy_fortigate
        

- hosts: virtual_connect
  vars_files:
  - passwords/ansible_vault.yml
  - vars/network-config.yml
  vars:
    ansible_connection: network_cli
    ansible_ssh_private_key_file: /home/user1/.ssh/id_rsa_ansibledeployment # Otherwise an error is thrown
  tasks:

  - name: Deploy VLANs on Virtual Connect
    tags: deploy_vc
    block:

    - name: Deploy VLANs on Virtual Connect
      ansible.builtin.include_tasks:
        file: tasks/deploy-virtualconnect-vlans.yml
        apply:
          tags: deploy_vc
      tags: deploy_vc


- hosts: vcenter
  gather_facts: no
  vars_files:
  - passwords/ansible_vault.yml
  - vars/network-config.yml 
  tasks:

  - name: Deploy VLANs on VMware
    tags: deploy_vmware
    delegate_to: localhost
    block:

    - name: Deploy VLANs on VMware
      ansible.builtin.include_tasks:
        file: tasks/deploy-vmware-vlans.yml
        apply:
          tags: vm
      tags: deploy_vmware
      vars:
        ansible_python_interpreter: /usr/bin/python3.9


- hosts: windows_dns
  # gather_facts: no
  vars_files:
  - passwords/ansible_vault.yml
  - vars/network-config.yml 
  tasks:

  - name: Deploy VLAN DHCP scopes on Windows DNS
    tags: deploy_dhcp
    block:

    - name: Deploy VLAN DHCP scopes on Windows DNS
      ansible.builtin.include_tasks:
        file: tasks/deploy-windows-dhcp-scopes.yml
        apply:
          tags: vm
      tags: deploy_dhcp


  - name: Deploy VLAN DHCP scope failovers on Windows DNS
    tags: deploy_dhcp
    become: yes
    become_method: runas
    block:

    - name: Deploy VLAN DHCP scope failovers on Windows DNS
      ansible.builtin.include_tasks:
        file: tasks/deploy-windows-dhcp-scopes-failovers.yml
        apply:
          tags: vm
      tags: deploy_dhcp