--- 
- import_playbook: check_all.yml

- name: Deploy VMs
  hosts: rdlokd3wrkr01.rdlabo.local # rhel8_vms # 
  gather_facts: false
  vars_files:
  - passwords/ansible_vault.yml

  tasks:

  # - name: Biep 
  #   ansible.builtin.debug:
  #     msg: "Test: {{ vars.community_vmware_vmware__guest.folder }}"
    #loop: "{{ groups.rhel8_vms }}"

  - name: Deploy VMs
    ansible.builtin.include_tasks: tasks/deploy-vmware-vms-from-template.yml

  - name: Check alive
    debug:
      msg: 'Biep from host!'
  
  
  
  
  # - name: Biep list detail
  #   ansible.builtin.debug:
  #     msg: "{{ item.community.vmware.vmware_guest.state }}"
  #   when: hostvars[item]['inventory_hostname'] == 'rdlokd3infr02.rdlabo.local'
  #   loop: "{{ rhel8_vms }}"

# - name: Configure VMs
#   hosts: vcenter_vms
#   gather_facts: false

#   tasks:
#   - name: Biep
#     ansible.builtin.debug:
#       msg: "{{ item }}"
#     loop: "{{ rhel8_vms }}"


- name: Tasks
  hosts: localhost 
  connection: local 
  gather_facts: false 

  tasks:
  - name: Biep
    ansible.builtin.debug:
      msg: "biep" 
