---
# roles:
# - geerlingguy.glusterfs
# - bertvv.bind
# - bertvv.dhcp # not updated anymore
# - src: https://github.com/bertvv/ansible-role-dhcp.git
#   name: bertvv.dhcp

collections:
- ovirt.ovirt
# - gluster.gluster
- ansible.posix
- community.vmware
- community.okd
- community.windows
- community.general
- citrix.adc
- kubernetes.core # Used to be community.kubernetes
- git+https://github.com/vmware/ansible-for-nsxt
- arubanetworks.aos_switch
- fortinet.fortios

# Install with:
# - ansible-galaxy collection install -r requirements.yml
# - ansible-galaxy role install -r requirements.yml 
# This will install external roles & collections to the user's /home/<user>/.ansible/ dir