---
- hosts: openshift_bootstrap_nodes
  gather_facts: false
  vars_files:
  - passwords/ansible_vault.yml
  - vars/network-config.yml
  - group_vars/vcenter_vms.yml
  tasks:
  - delegate_to: localhost
    block:
    - set_fact:
        alist:
        - name: VLAN669-RD Labo Large
          device_type: vmxnet3
          connected: True
          start_connected: True
          label: Network adapter 2
          mac: 00:05:69:aa:aa:06

- hosts: localhost
  gather_facts: false
  vars:
    dict1:
    - key1: value1
      key2: value2
    - key1: valuea
      key2: valueb
    dict2:
    -  key3: value3
    -  key3: valuec
  tasks:
    # - name: Merge dict2 to dict1
    #   set_fact:
    #     dict1: "{{ dict1|map('combine', item) }}"
    #   loop: "{{ dict2 }}"
    # - name: Print dict1
    #   debug:
    #     var: dict1
        
    # - name: Zip dict2 to dict1
    #   set_fact:
    #     dict1: "{{ dict1|zip(dict2)|map('combine') }}"
    # - name: Print dict1
    #   debug:
    #     var: dict1
    - name: Print filtered dict1
      debug:
        var: dict1 |map(attribute='key1')|map('community.general.dict_kv', 'tempkey') | list
    - name: Zip dict2 to dict1
      set_fact:
        dict1: "{{ dict1|zip(dict2)|map('combine') }}"
    - name: Print dict1
      debug:
        var: dict1

      # - name: Add Ingress LB TLS secret
      #   kubernetes.core.k8s:
      #     state: present
      #     definition:
      #       api_version: v1
      #       kind: Secret
      #       metadata:
      #         name: lb-chain-secret
      #         namespace: openshift-ingress
      #       type: kubernetes.io/tls
      #       data:
      #         tls.crt: "{{ lookup('file', '{{ openshift_config_dir }}/{{ ncp_config.openshift_tls_certificate_name }}.crt', rstrip=false) | b64encode }}"
      #         tls.key: "{{ lookup('file', '{{ openshift_config_dir }}/{{ ncp_config.openshift_tls_certificate_name }}.key', rstrip=false) | b64encode }}"


      # - name: Patch Ingress Controllers to use the LB secret
      #   kubernetes.core.k8s_json_patch:
      #     api_version: operator.openshift.io/v1
      #     namespace: openshift-ingress-operator
      #     kind: IngressController
      #     name: default
      #     patch:
      #     - op: add
      #       path: "/spec/defaultCertificate"
      #       value:
      #         name: lb-chain-secret

      # - debug:
      #     msg: "{{ lookup('file', '{{ openshift_config_dir }}/{{ ncp_config.openshift_tls_certificate_name }}.crt') | to_nice_json | b64encode }}"

      # - debug:
      #     msg: "{{ lookup('file', '{{ openshift_config_dir }}/{{ ncp_config.openshift_tls_certificate_name }}.crt', rstrip=false) | b64encode }}"

