---
- hosts: openshift_bootstrap_nodes
  gather_facts: false
  vars_files:
  - passwords/ansible_vault.yml
  - vars/network-config.yml
  - group_vars/vcenter_vms.yml
  tasks:
  - delegate_to: localhost
    block:
    - set_fact:
        alist:
        - name: VLAN669-RD Labo Large
          device_type: vmxnet3
          connected: True
          start_connected: True
          label: Network adapter 2
          mac: 00:05:69:aa:aa:06
- hosts: localhost
  gather_facts: false
  vars:
    my_list:
      - apple
      - banana
      - cherry
      - date
    specific_string: "b"
    install_operator_csv_nameprefix: odf-operator
    r_install_plans:
      resources:
      - apiVersion: operators.coreos.com/v1alpha1
        kind: InstallPlan
        metadata:
          creationTimestamp: "2023-05-17T09:14:56Z"
          generateName: install-
          generation: 1
          labels:
            operators.coreos.com/mcg-operator.openshift-storage: ""
            operators.coreos.com/ocs-operator.openshift-storage: ""
            operators.coreos.com/odf-csi-addons-operator.openshift-storage: ""
            operators.coreos.com/odf-operator.openshift-storage: ""
          name: install-8w54m
          namespace: openshift-storage
          ownerReferences:
          - apiVersion: operators.coreos.com/v1alpha1
            blockOwnerDeletion: false
            controller: false
            kind: Subscription
            name: odf-operator
            uid: a0613e49-e3f6-44a4-bf6f-a2b05a755005
          resourceVersion: "2627451"
          uid: ba238702-9542-4692-a4bc-a6b92c404049
        spec:
          approval: Automatic
          approved: true
          clusterServiceVersionNames:
          - odf-csi-addons-operator.v4.11.7
          - odf-operator.v4.11.7
          - ocs-operator.v4.11.7
          - mcg-operator.v4.11.7
          generation: 1
        status:
          catalogSources:
          - redhat-operators
          conditions:
          - lastTransitionTime: "2023-05-17T09:15:29Z"
            lastUpdateTime: "2023-05-17T09:15:29Z"
            status: "True"
            type: Installed
          phase: Complete


  tasks:
    - name: Check if any item in the list starts with a specific string
      debug:
        msg: "Found items: {{ my_list | json_query(query) }}"
      vars:
        query: "[?starts_with(@, '{{ specific_string }}')]"

    - name: Test
      debug:
        msg: "{{ r_install_plans.resources | to_json | from_json | json_query( query2 ) }}"
      vars:
        query: >-
          [?starts_with(spec.approval, 'Automatic') && status.phase ]
        query2: >-
          [?contains(spec.clusterServiceVersionNames[] | join(',', @), '{{install_operator_csv_nameprefix}}') && status.phase ]
        _2query: >-
          [?starts_with(spec.clusterServiceVersionNames[0], 'odf-csi-addons-operator.v4.11.7') && status.phase ]


- hosts: localhost
  gather_facts: false
  vars:
    my_list_of_dicts:
      - key1: value1
        key2: value2
      - key1: value3
        key2: value4
      - key1: value5
        key2: value6

  tasks:
    - name: Select the first dictionary as a single-item list
      set_fact:
        first_dict_list: "{{ [] + [my_list_of_dicts | first] }}"

    - name: Select the first dictionary as a single-item list
      set_fact:
        first_dict_list: "{{ [my_list_of_dicts | first] | list }}"

    - name: Display the first dictionary list
      debug:
        var: first_dict_list