---

- name: Looping SUS'es per VLAN
  include_tasks: deploy-virtualconnect-serverportmap-sus.yml
  loop: "{{ virtual_connect_shared_uplinks_sets }}"
  loop_control:
    label: "VLAN '{{ vlan.name}}' - SUS '{{ sus }}'"
    loop_var: sus
    index_var: sus_index
