---
- name: Create Service Groups
  citrix.adc.citrix_adc_servicegroup:
    nsip: "{{ citrix_ip }}"
    nitro_user: "{{ citrix_username_unecnrypted }}"
    nitro_pass: "{{ citrix_password_unecnrypted }}"
    validate_certs: false
    save_config: true
    state: present
    servicegroupname: "{{ item.name }}"
    servicetype: "{{ item.servicetype }}"
    servicemembers:
      mode: "{{ item.mode }}"
      attributes: "{{ item.members }}"
  with_items: "{{ citrix_vservers | map(attribute='servicegroup') }}"
  ignore_errors: True
  register: config

- name: Fail if there is an error other than the identical configuration
  fail:
    msg: "Following errors present: {{ item.loglines }}"
  loop: "{{ config.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  when: item.failed and not item.loglines is search('configured_already_present')
  
- name: Save running configuration
  citrix.adc.citrix_adc_save_config:
    nsip: "{{ citrix_ip }}"
    nitro_user: "{{ citrix_username_unecnrypted }}"
    nitro_pass: "{{ citrix_password_unecnrypted }}"
    validate_certs: false
  run_once: true
  ignore_errors: True
  register: config_save

- name: Fail if there is an error other than the identical configuration
  fail:
    msg: "Following errors present: {{ config_save.loglines }}"
  when: config_save.failed and not config_save.loglines is search('configured_already_present')
  