---

- name: Copy the new public SSH key to VM
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/'+deployment_ssh_filename+'.pub') }}"

# - name: Ensure that the ansible_become_password is changed from the template password to the new password
#   set_fact:
#     ansible_become_password: "{{ deployment_password }}"

- name: Reset Ansible connections
  meta: reset_connection

- name: Change root's password from the template one to the new one
  ansible.builtin.user:
    name: root
    password: "{{ deployment_password | password_hash('sha512') }}"
  become: yes
  become_user: root
  ignore_errors: yes
  register: ansible_user_passwordcheck

- name: Change {{ ansible_user }}'s password from the template one to the new one
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    password: "{{ deployment_password | password_hash('sha512') }}"
  become: yes
  become_user: root
  ignore_errors: yes


- name: Retry changing root's password using the template password if the previous try failed
  block:
  - set_fact:
      ansible_become_password: "{{ deployment_template_password }}"
  - ansible.builtin.user:
      name: root
      password: "{{ deployment_password | password_hash('sha512') }}"
    become: yes
    become_user: root
    ignore_errors: yes
  when: ansible_user_passwordcheck.failed


- name: Retry changing {{ ansible_user }}'s password using the template password if the previous try failed
  block:
  - set_fact:
      ansible_become_password: "{{ deployment_template_password }}"
  - ansible.builtin.user:
      name: "{{ ansible_user }}"
      password: "{{ deployment_password | password_hash('sha512') }}"
    become: yes
    become_user: root
    ignore_errors: yes
  when: ansible_user_passwordcheck.failed

- name: Ensure that the ansible_become_password is changed back to the new password
  set_fact:
    ansible_become_password: "{{ deployment_password }}"
  when: ansible_user_passwordcheck.failed

- name: Reset Ansible connection
  meta: reset_connection


# ToDo: remove old SSH cert ?