---
# - name: check var
#   debug:
#     msg: "{{ vars.target_group_dns }}"
# # - name: halt
# #   fail: {}
# - name: Debug check names
#   debug:
#     msg: "Name '{{ inventory_hostname }}', domain '{{ inventory_hostname[inventory_hostname.index('.')+1:] }}', IP '{{ vars.ip }}', vlans '{{ vars.vlans }}'"

# - name: Ensure primary zone is present
#   community.windows.win_dns_zone:
#     name: 
#     replication: domain
#     type: primary
#     state: present

- name: Find matching reverse lookup zone
  set_fact:
    found_revlookupzonename: "{{ item.revlookupzonename }}"
    found_fwdlookupzonename: "{{ item.fwdlookupzonename }}"
  loop: "{{ vars.vlans }}"
  when: item.name == vars.custom_community_vmware_vmware__guest.networks[0].name

- name: "DNS Forward records: name - value - zone"
  debug:
    msg: "{{ inventory_hostname | replace('.' + vars.found_fwdlookupzonename , '') }}, {{ vars.ip }}, {{ vars.found_fwdlookupzonename }}"
           
- name: Create Windows DNS A record
  community.windows.win_dns_record:
    name: "{{ inventory_hostname | replace('.' + vars.found_fwdlookupzonename , '') }}"
    type: A
    value: "{{ vars.ip }}"
    zone: "{{ vars.found_fwdlookupzonename }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups.windows_dns }}"

- name: "DNS Reverse records: name - value - zone"
  debug:
    msg: "{{ vars.ip[vars.found_revlookupzonename.index('.in-addr.arpa')+1:] }}, {{ inventory_hostname_short }}, {{ vars.found_revlookupzonename }}"

- name: Create Windows DNS PTR record
  community.windows.win_dns_record:
    name: "{{ vars.ip[vars.found_revlookupzonename.index('.in-addr.arpa')+1:] }}"
    type: PTR
    value: "{{ inventory_hostname_short }}" # "{{ inventory_hostname | replace(vars.found_fwdlookupzonename , '') }}"
    zone: "{{ vars.found_revlookupzonename }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups.windows_dns }}"
  