---

- name: Fail if no single forward lookup zone is found 
  fail:
    msg: "No single forward lookup zone found for {{ vars.custom_community_vmware_vmware__guest.networks[0].name }}, there are 
          {{ vars.vlans | selectattr('name','eq', vars.custom_community_vmware_vmware__guest.networks[0].name) | map(attribute='revlookupzonename') | list | length }}"
  when: vars.vlans | selectattr('name','eq', vars.custom_community_vmware_vmware__guest.networks[0].name) | map(attribute='revlookupzonename') | list | length != 1

- name: Find matching reverse lookup zone
  set_fact:
    found_revlookupzonename: "{{ (vars.vlans | selectattr('name','eq', vars.custom_community_vmware_vmware__guest.networks[0].name) | map(attribute='revlookupzonename') | list)[0] }}"
    found_fwdlookupzonename: "{{ (vars.vlans | selectattr('name','eq', vars.custom_community_vmware_vmware__guest.networks[0].name) | map(attribute='fwdlookupzonename') | list)[0] }}"

- name: "DNS Forward records: name - value - zone"
  debug:
    msg: "{{ inventory_hostname | replace('.' + vars.found_fwdlookupzonename , '') }}, {{ vars.nics[0].ip }}, {{ vars.found_fwdlookupzonename }}"

- name: Ensure primary zone is present
  community.windows.win_dns_zone:
    name: "{{ found_fwdlookupzonename }}"
    replication: domain
    type: primary
    state: present
  delegate_to: "{{ item }}"
  with_items: "{{ groups.windows_dns }}"

- name: Create Windows DNS A record
  community.windows.win_dns_record:
    name: "{{ inventory_hostname | replace('.' + vars.found_fwdlookupzonename , '') }}"
    type: A
    value: "{{ vars.nics[0].ip }}"
    zone: "{{ vars.found_fwdlookupzonename }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups.windows_dns }}"

- name: "DNS Reverse records: name - value - zone"
  debug:
    msg: "{{ vars.nics[0].ip[vars.found_revlookupzonename.index('.in-addr.arpa')+1:] }}, {{ inventory_hostname_short }}, {{ vars.found_revlookupzonename }}"

- name: Create Windows DNS Reverse Lookup zone
  community.windows.win_dns_zone:
    name: "{{ vars.found_revlookupzonename }}"
    replication: domain
    type: primary
    state: present
  throttle: 1
  delegate_to: "{{ item }}"
  with_items: "{{ groups.windows_dns }}"

- name: Create Windows DNS PTR record
  community.windows.win_dns_record:
    name: "{{ vars.nics[0].ip[vars.found_revlookupzonename.index('.in-addr.arpa')+1:] }}"
    type: PTR
    value: "{{ inventory_hostname_short }}" # "{{ inventory_hostname | replace(vars.found_fwdlookupzonename , '') }}"
    zone: "{{ vars.found_revlookupzonename }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups.windows_dns }}"
  