---

- name: Looping Virtual Servers
  include_tasks: deploy-citrix-vserver.yml
  loop: "{{ vars.citrix_vservers }}"
  loop_control:
    label: "Virtual Server '{{ citrix_vserver.name }}'"
    loop_var: citrix_vserver
