---
# - name: Debug check names
#   debug:
#     msg: "Name '{{ inventory_hostname }}', domain '{{ inventory_hostname[inventory_hostname.index('.')+1:] }}', IP '{{ vars.nics[0].ip }}', vlans '{{ vars.vlans }}'"

- name: Find matching reverse lookup zone
  set_fact:
    found_revlookupzonename: "{{ item.revlookupzonename }}"
  loop: "{{ vars.vlans }}"
  when: item.name == vars.vmware_networkportgroup

# - name: check
#   debug:
#     msg: "{{ vars.nics[0].ip[vars.found_revlookupzonename.index('.in-addr.arpa')+1:] }}"
#     msg: "{{ inventory_hostname }}, {{ vars.nics[0].ip }}, {{ inventory_hostname[inventory_hostname.index('.')+1:] }}"

- name: Create Windows DNS A record
  community.windows.win_dns_record:
    name: "{{ inventory_hostname_short }}"
    type: A
    value: "{{ vars.nics[0].ip }}"
    zone: "{{ inventory_hostname[inventory_hostname.index('.')+1:] }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups.windows_dns }}"

- name: Create Windows DNS PTR record
  community.windows.win_dns_record:
    name: "{{ vars.nics[0].ip[vars.found_revlookupzonename.index('.in-addr.arpa')+1:] }}"
    type: PTR
    value: "{{ inventory_hostname }}"
    zone: "{{ vars.found_revlookupzonename }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups.windows_dns }}"