---
- name: Create DNS records for api and api-int
  when: vars.type == 'bootstrap'
  block:

  - name: Fail if no single forward lookup zone is found 
    fail:
      msg: "No single forward lookup zone found for {{ vars.openshift_api_vlan }}, there are 
            {{ vars.vlans | selectattr('name','eq', vars.openshift_api_vlan) | map(attribute='revlookupzonename') | list | length }}"
    when: vars.vlans | selectattr('name','eq', vars.openshift_api_vlan) | map(attribute='revlookupzonename') | list | length != 1

  - name: Find matching reverse lookup zone
    set_fact:
      found_revlookupzonename: "{{ (vars.vlans | selectattr('name','eq', vars.openshift_api_vlan) | map(attribute='revlookupzonename') | list)[0] }}"
      found_fwdlookupzonename: "{{ (vars.vlans | selectattr('name','eq', vars.openshift_api_vlan) | map(attribute='fwdlookupzonename') | list)[0] }}"

  - name: Create Windows DNS A record for 'api'
    community.windows.win_dns_record:
      name: "{{ openshift_api_url | replace('.' + vars.found_fwdlookupzonename , '') }}"
      type: A
      value: "{{ vars.openshift_api_ip }}"
      zone: "{{ vars.found_fwdlookupzonename }}"
    delegate_to: "{{ item }}"
    with_items: "{{ groups.windows_dns }}"

  - name: Create Windows DNS A record for 'api-int'
    community.windows.win_dns_record:
      name: "{{ openshift_api_int_url | replace('.' + vars.found_fwdlookupzonename , '') }}"
      type: A
      value: "{{ vars.openshift_api_ip }}"
      zone: "{{ vars.found_fwdlookupzonename }}"
    delegate_to: "{{ item }}"
    with_items: "{{ groups.windows_dns }}"

  - name: Create Windows DNS Reverse Lookup zone
    community.windows.win_dns_zone:
      name: "{{ vars.found_revlookupzonename }}"
      replication: domain
      type: primary
      state: present
    throttle: 1
    delegate_to: "{{ item }}"
    with_items: "{{ groups.windows_dns }}"

  - name: Create Windows DNS PTR record for 'api' & 'api-int'
    community.windows.win_dns_record:
      name: "{{ vars.openshift_api_ip[vars.found_revlookupzonename.index('.in-addr.arpa')+1:] }}"
      type: PTR
      value:
      - "{{ openshift_api_url }}"
      - "{{ openshift_api_int_url }}"
      zone: "{{ vars.found_revlookupzonename }}"
    delegate_to: "{{ item }}"
    with_items: "{{ groups.windows_dns }}"
    

- name: Create DNS records for apps
  when: vars.type == 'bootstrap'
  block:

  - name: Fail if no single forward lookup zone is found 
    fail:
      msg: "No single forward lookup zone found for {{ vars.openshift_ingress_vlan }}, there are 
            {{ vars.vlans | selectattr('name','eq', vars.openshift_ingress_vlan) | map(attribute='revlookupzonename') | list | length }}"
    when: vars.vlans | selectattr('name','eq', vars.openshift_ingress_vlan) | map(attribute='revlookupzonename') | list | length != 1

  - name: Find matching reverse lookup zone
    set_fact:
      found_revlookupzonename: "{{ (vars.vlans | selectattr('name','eq', vars.openshift_ingress_vlan) | map(attribute='revlookupzonename') | list)[0] }}"
      found_fwdlookupzonename: "{{ (vars.vlans | selectattr('name','eq', vars.openshift_ingress_vlan) | map(attribute='fwdlookupzonename') | list)[0] }}"

  - name: Create Windows DNS A record for 'apps'
    community.windows.win_dns_record:
      name: "{{ openshift_ingress_url | replace('.' + vars.found_fwdlookupzonename , '') }}"
      type: A
      value: "{{ vars.openshift_ingress_ip }}"
      zone: "{{ vars.found_fwdlookupzonename }}"
    delegate_to: "{{ item }}"
    with_items: "{{ groups.windows_dns }}"

  - name: Create Windows DNS Reverse Lookup zone
    community.windows.win_dns_zone:
      name: "{{ vars.found_revlookupzonename }}"
      replication: domain
      type: primary
      state: present
    throttle: 1
    delegate_to: "{{ item }}"
    with_items: "{{ groups.windows_dns }}"

  - name: Create Windows DNS PTR record for 'apps'
    community.windows.win_dns_record:
      name: "{{ vars.openshift_ingress_ip[vars.found_revlookupzonename.index('.in-addr.arpa')+1:] }}"
      type: PTR
      value: "{{ openshift_ingress_url }}"
      zone: "{{ vars.found_revlookupzonename }}"
    delegate_to: "{{ item }}"
    with_items: "{{ groups.windows_dns }}"