---
- name: Create Service Groups
  citrix.adc.citrix_adc_servicegroup:
    nsip: "{{ citrix_ip }}"
    nitro_user: "{{ citrix_username_unecnrypted }}"
    nitro_pass: "{{ citrix_password_unecnrypted }}"
    validate_certs: false
    save_config: true
    state: present
    servicegroupname: "{{ item.name }}"
    servicetype: "{{ item.servicetype }}"
    servicemembers:
      mode: "{{ item.mode }}"
      attributes: "{{ item.members }}"
  with_items: "{{ citrix_vservers | map(attribute='servicegroup') }}"
  
- name: Save running configuration
  citrix.adc.citrix_adc_save_config:
    nsip: "{{ citrix_ip }}"
    nitro_user: "{{ citrix_username_unecnrypted }}"
    nitro_pass: "{{ citrix_password_unecnrypted }}"
    validate_certs: false