---

- name: Install docker repo
  shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  become: yes

- name: Deploy Docker
  yum:
    name: docker-1.13.1
    state: present
  become: yes

- name: Read device information (always use unit when probing)
  community.general.parted: device=/dev/sdb unit=MiB
  register: sdb_info
  become: yes
  
- name: Create a new partition to fill all available space on the second drive
  community.general.parted:
    device: /dev/sdb
    number: "{{ (sdb_info.partitions | length) + 1 }}"
    flags: [ lvm ]
    part_end: "100%"
    state: present
  become: yes
  when: sdb_info.partitions == 0

- name: Check presence of VG
  command: vgdisplay vg-docker
  register: vgdisplay
  ignore_errors: yes
  become: yes

- name: Extend the vg to the PV's new maximum size
  community.general.lvg:
    vg: vg-docker
    pvs: /dev/sdb1
    pvresize: yes
  become: yes
  when: vgdisplay.failed

- name: Check whether storage config was already added to docker-storage-setup
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/docker-storage-setup
    state: present
    line: "VG=vg-docker"
  check_mode: yes
  register: storage_setup_linecheck

# - name: temp
#   lineinfile:
#     regexp: "VG=vg-docker"
#     state: absent
#     path: /etc/sysconfig/docker-storage-setup
#   become: yes
# - name: temp
#   lineinfile:
#     regexp: "SETUP_LVM_THIN_POOL=yes"
#     state: absent
#     path: /etc/sysconfig/docker-storage-setup
#   become: yes
# - name: pause
#   fail: {}

- name: Add storage config to docker-storage-setup
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/docker-storage-setup
    insertafter: EOF
    state: present
    line: "VG=vg-docker\nDEVS=/dev/sdb\nCONTAINER_ROOT_LV_NAME=lv-docker\nCONTAINER_ROOT_LV_SIZE=100%FREE\nCONTAINER_ROOT_LV_MOUNT_PATH=/var/lib/docker"
  become: yes
  when: storage_setup_linecheck is changed

- name: Execute docker storage setup
  command: docker-storage-setup
  become: yes
  register: storage_setup_output
  when: storage_setup_linecheck is changed

- name: Show output if setup is performed
  debug:
    msg: "{{  storage_setup_output.stdout }}"
  when: storage_setup_linecheck is changed

- name: Show error output if setup is performed
  debug:
    msg: "{{  storage_setup_output.stderr }}"
  when: storage_setup_linecheck is changed

- name: Check that the docker service is enabled & started
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: restarted
  become: yes

- name: Deploy glusterf-fuse
  yum:
    name: glusterfs-fuse
    state: present
  become: yes