---

- name: Show VM networks with IPs and MACs
  debug:
    msg: " -- Network {{ index_current }} --\n{{ item | to_nice_yaml(indent=4) }} -- IP & MAC --\n{{ vars.nics[index_current] | to_nice_yaml(indent=4) }}"
  loop: "{{ vars.community_vmware_vmware__guest.networks }}"
  loop_control:
    extended: true
    index_var: index_current
    
- name: Get VM facts pre-deploy
  retries: 3
  delay: 10
  ignore_errors: true
  community.vmware.vmware_guest:
    validate_certs: "{{ validate_certs | default(false) }}"
    hostname: "{{ vcenter_hostname | default(lookup('env', 'VMWARE_HOST')) }}"
    username: "{{ vcenter_username | default(lookup('env', 'VMWARE_USER')) }}"
    password: "{{ vcenter_password | default(lookup('env', 'VMWARE_PASSWORD')) }}"  
    datacenter: "{{ vars.community_vmware_vmware__guest.datacenter }}"
    name: "{{ inventory_hostname_short }}"
  delegate_to: localhost
  register: facts_pre_nicaddition
  
- name: Update VMs' Advanced Settings to allow VMware-reserved MACs
  throttle: "{{ parallel_deployments }}"
  retries: 3
  delay: 10
  community.vmware.vmware_guest:
    validate_certs: "{{ validate_certs | default(false) }}"
    hostname: "{{ vcenter_hostname | default(lookup('env', 'VMWARE_HOST')) }}"
    username: "{{ vcenter_username | default(lookup('env', 'VMWARE_USER')) }}"
    password: "{{ vcenter_password | default(lookup('env', 'VMWARE_PASSWORD')) }}"
    name: "{{ inventory_hostname_short }}"
    state: present
    advanced_settings:
    - key: "ethernet{{ index_current }}.checkMACAddress"
      value: false
  delegate_to: localhost
  when: vars.community_vmware_vmware__guest.advanced_settings is defined
  loop: "{{ vars.community_vmware_vmware__guest.networks }}"
  loop_control:
    extended: true
    index_var: index_current

- name: Deploy the NIC
  community.vmware.vmware_guest_network:
    validate_certs: "{{ validate_certs | default(false) }}"
    hostname: "{{ vcenter_hostname | default(lookup('env', 'VMWARE_HOST')) }}"
    username: "{{ vcenter_username | default(lookup('env', 'VMWARE_USER')) }}"
    password: "{{ vcenter_password | default(lookup('env', 'VMWARE_PASSWORD')) }}"
    datacenter: "{{ vars.community_vmware_vmware__guest.datacenter }}"
    name: "{{ inventory_hostname_short }}"
    state: present
    network_name: "{{ item.name }}"
    device_type: "{{ item.device_type | default('vmxnet3') }}"
    connected: "{{ item.connected | default('true') }}"
    start_connected: "{{ item.start_connected | default('true') }}"
    mac_address: "{{ vars.nics[index_current].mac | default (omit)}}"
    label: "{{ item.label | default (omit)}}"
  loop: "{{ vars.community_vmware_vmware__guest.networks }}"
  loop_control:
    extended: true
    index_var: index_current
    pause: 5

  delegate_to: localhost
  # register: nic_attch
