---
- name: Create NSX Segment
  vmware.ansible_for_nsxt.nsxt_policy_segment:
    hostname: "{{ nsx_hostname }}"
    username: "{{ vmware_nsx_username }}"
    password: "{{ vmware_nsx_password }}"
    validate_certs: False
    display_name: "{{ item.name }}"
    state: present
    transport_zone_display_name: "{{ item.transport_zone_display_name }}"
    subnets: "{{ item.subnets }}"
    connectivity_path: "{{ item.connectivity_path }}"
    admin_state: UP

  with_items: "{{ nsx_segment_config }}"
  delegate_to: localhost
  when: nsx_integration
  throttle: 1
  run_once: true
