---

- name: Debug check names
  debug:
    msg: "Name '{{ inventory_hostname }}', domain '{{ inventory_hostname[inventory_hostname.index('.')+1:] }}', IP '{{ vars.ip }}', vlans '{{ vars.vlans }}'"

- name: Find matching reverse lookup zone
  set_fact:
    found_revlookupzonename: "{{ item.revlookupzonename }}"
  loop: "{{ vars.vlans }}"
  when: item.name == vars.vmware_networkportgroup

- name: Create Windows DNS A record
  community.windows.win_dns_record:
    name: "{{ inventory_hostname }}"
    type: A
    value: "{{ vars.ip }}"
    zone: "{{ inventory_hostname[inventory_hostname.index('.')+1:] }}"
  delegate_to: windows_dns

- name: Create Windows DNS PTR record
  community.windows.win_dns_record:
    name: "{{ vars.ip }}"
    type: PTR lookup
    value: "{{ inventory_hostname_short }}"
    zone: "{{ vars.found_revlookupzonename }}"
  delegate_to: windows_dns