---

- name: Remove existing VM host keys by name and IP
  shell: "ssh-keygen -R {{ item }}"
  with_items:
   - "{{ vars.IP }}"
   - "{{ vars.inventory_hostname }}"
   - "{{ vars.inventory_hostname_short }}"
  ignore_errors: yes
  delegate_to: localhost

- name: Query the new SSH host key
  shell: "ssh-keyscan -T 10 {{ vars.ip }},{{ inventory_hostname }}"
  register: ssh_results
  retries: 12
  delay: 5
  until: ssh_results is not failed
  delegate_to: localhost

- name: Write the new SSH host key to known hosts @ {{ lookup('env','HOME') + '/.ssh/known_hosts' }}
  known_hosts:
    path: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    name: "{{ inventory_hostname }}"
    key: "{{ ssh_results.stdout }}"
    state: present 
  delegate_to: localhost