---
- name: Remove the old known host keys for this VM
  throttle: 1 # This prevents concurrent access to the known_hosts file
  known_hosts:
    path: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    name: "{{ inventory_hostname }}"
    state: absent 
  delegate_to: localhost

- name: Query the new SSH host key
  shell: "ssh-keyscan -T 10 -t ssh-rsa {{ vars.nics[0].ip }},{{ inventory_hostname }}"
  register: ssh_results_rsa_key
  retries: 12
  delay: 5
  until: ssh_results_rsa_key is not failed
  delegate_to: localhost

- name: Write the new SSH host key to known hosts @ {{ lookup('env','HOME') + '/.ssh/known_hosts' }}
  throttle: 1 # This prevents concurrent access to the known_hosts file
  known_hosts:
    path: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    name: "{{ inventory_hostname }}"
    key: "{{ ssh_results_rsa_key.stdout }}"
    state: present 
  delegate_to: localhost