dns_servers:
- 10.255.254.102
- 10.255.254.101
dns_domain: rdlabo.local
dhcp_server: 10.255.254.102
vlans:
- name: 665-RD Labo
  vlan_id: 665
  network: 10.255.254.0
  netmask: 255.255.255.0
  gateway: 10.255.254.254
  revlookupzonename: 254.255.10.in-addr.arpa
  fwdlookupzonename: rdlabo.local
  jumbo: yes
  vlan_tag:
  - uplink_type: core
    tagged: yes
  fortigate_managed: no
# - name: 669-RD Labo Large
#   vlan_id: 669
#   network: 10.254.0.0
#   netmask: 255.255.128.0
#   gateway: 10.254.0.1
#   revlookupzonename: 0.254.10.in-addr.arpa
#   fwdlookupzonename: rdlabo.local
#   jumbo: yes
#   vlan_tag:
#   - uplink_type: core
#     tagged: yes
#   fortigate_managed: no
# - name: 666-BURA
#   vlan_id: 666
#   network: 10.255.255.0
#   netmask: 255.255.255.0
#   gateway: 10.255.255.254
#   revlookupzonename: 255.255.10.in-addr.arpa
#   fwdlookupzonename: rdlabo.local
#   jumbo: yes
#   vlan_tag:
#   - uplink_type: core
#     tagged: yes
#   fortigate_managed: no
# - name: 701-OpenShift1
#   vlan_id: 701
#   network: 10.255.242.0
#   netmask: 255.255.255.0
#   gateway: 10.255.242.254
#   revlookupzonename: 242.255.10.in-addr.arpa
#   fwdlookupzonename: rdlabo.local
#   jumbo: yes
#   vlan_tag:
#   - uplink_type: core
#     tagged: yes
#   fortigate_managed: no
# - name: 702-OpenShift2
#   vlan_id: 702
#   network: 10.255.244.0
#   netmask: 255.255.255.0
#   gateway: 10.255.244.254
#   revlookupzonename: 244.255.10.in-addr.arpa
#   fwdlookupzonename: rdlabo.local
#   jumbo: yes
#   vlan_tag:
#   - uplink_type: core
#     tagged: yes
#   fortigate_managed: no
# - name: 703-OpenShift3
#   vlan_id: 703
#   network: 10.255.245.0
#   netmask: 255.255.255.0
#   gateway: 10.255.245.254
#   revlookupzonename: 245.255.10.in-addr.arpa
#   fwdlookupzonename: rdlabo.local
#   jumbo: yes
#   vlan_tag:
#   - uplink_type: core
#     tagged: yes
#   fortigate_managed: no
# - name: 704-OpenShift4
#   vlan_id: 704
#   network: 10.255.246.0
#   netmask: 255.255.255.0
#   gateway: 10.255.246.254
#   revlookupzonename: 246.255.10.in-addr.arpa
#   fwdlookupzonename: rdlabo.local
#   jumbo: yes
#   vlan_tag:
#   - uplink_type: core
#     tagged: yes
#   fortigate_managed: no
# - name: NSX-OpenShift-UPI-NSX
#   network: 10.200.0.0
#   netmask: 255.255.255.0
#   gateway: 10.200.0.254
#   revlookupzonename: 0.200.10.in-addr.arpa
#   fwdlookupzonename: rdlabo.local
#   jumbo: yes
#   fortigate_managed: no
# - name: NSX-OpenShift-UPI-NSX-Workers
#   network: 10.201.0.0
#   netmask: 255.255.255.0
#   gateway: 10.201.0.254
#   revlookupzonename: 0.201.10.in-addr.arpa
#   fwdlookupzonename: rdlabo.local
#   jumbo: yes
#   fortigate_managed: no
# - name: NSX-OpenShift-UPI-NSX-Infra
#   network: 10.201.1.0
#   netmask: 255.255.255.0
#   gateway: 10.201.1.254
#   revlookupzonename: 1.201.10.in-addr.arpa
#   fwdlookupzonename: rdlabo.local
#   jumbo: yes
#   fortigate_managed: no
# - name: NSX-OpenShift-UPI-NSX-Storage
#   network: 10.201.2.0
#   netmask: 255.255.255.0
#   gateway: 10.201.2.254
#   revlookupzonename: 2.201.10.in-addr.arpa
#   fwdlookupzonename: rdlabo.local
#   jumbo: yes
#   fortigate_managed: no
- name: NSX-OpenShift-ClientSubnet
  network: 10.10.0.0
  netmask: 255.255.255.0
  gateway: 10.10.0.254
  revlookupzonename: 0.10.10.in-addr.arpa
  fwdlookupzonename: rdlabo.local
  jumbo: yes
  fortigate_managed: no
- name: 710-NSX-OPENSHIFTDEV-ExtLB-Mgmt
  vlan_id: 710
  network: 10.202.0.0
  netmask: 255.255.255.0
  gateway: 10.202.0.254
  revlookupzonename: 0.202.10.in-addr.arpa
  fwdlookupzonename: realdolmencloud.com
  jumbo: yes
  vlan_tag:
  - uplink_type: core
    tagged: yes
  fortigate_managed: yes
- name: 711-NSX-OPENSHIFTDEV-ExtLB-Apps
  vlan_id: 711
  network: 10.202.1.0
  netmask: 255.255.255.0
  gateway: 10.202.1.254
  revlookupzonename: 1.202.10.in-addr.arpa
  fwdlookupzonename: realdolmencloud.com
  jumbo: yes
  vlan_tag:
  - uplink_type: core
    tagged: yes
  fortigate_managed: yes
- name: 712-NSX-OPENSHIFTDEV-Master
  vlan_id: 712
  network: 10.202.2.0
  netmask: 255.255.255.0
  gateway: 10.202.2.254
  revlookupzonename: 2.202.10.in-addr.arpa
  fwdlookupzonename: rdlabo.local
  jumbo: yes
  vlan_tag:
  - uplink_type: core
    tagged: yes
  fortigate_managed: yes
- name: 713-NSX-OPENSHIFTDEV-Infra
  vlan_id: 713
  network: 10.202.3.0
  netmask: 255.255.255.0
  gateway: 10.202.3.254
  revlookupzonename: 3.202.10.in-addr.arpa
  fwdlookupzonename: rdlabo.local
  jumbo: yes
  vlan_tag:
  - uplink_type: core
    tagged: yes
  fortigate_managed: yes
- name: 714-NSX-OPENSHIFTDEV-Storage
  vlan_id: 714
  network: 10.202.4.0
  netmask: 255.255.255.0
  gateway: 10.202.4.254
  revlookupzonename: 4.202.10.in-addr.arpa
  fwdlookupzonename: rdlabo.local
  jumbo: yes
  vlan_tag:
  - uplink_type: core
    tagged: yes
  fortigate_managed: yes
- name: 715-NSX-OPENSHIFTDEV-Worker
  vlan_id: 715
  network: 10.202.5.0
  netmask: 255.255.255.0
  gateway: 10.202.5.254
  revlookupzonename: 5.202.10.in-addr.arpa
  fwdlookupzonename: rdlabo.local
  jumbo: yes
  vlan_tag:
  - uplink_type: core
    tagged: yes
  fortigate_managed: yes
- name: 716-NSX-OPENSHIFTDEV-Worker-MOCK
  vlan_id: 716
  network: 10.202.6.0
  netmask: 255.255.255.0
  gateway: 10.202.6.254
  revlookupzonename: 6.202.10.in-addr.arpa
  fwdlookupzonename: rdlabo.local
  jumbo: yes
  vlan_tag:
  - uplink_type: core
    tagged: yes
  fortigate_managed: yes
- name: 717-NSX-OPENSHIFTDEV-MOCK-ClientSubnet
  vlan_id: 717
  network: 10.202.7.0
  netmask: 255.255.255.0
  gateway: 10.202.7.254
  revlookupzonename: 7.202.10.in-addr.arpa
  fwdlookupzonename: mock.local
  jumbo: yes
  vlan_tag:
  - uplink_type: core
    tagged: yes
  fortigate_managed: yes