---
# vars:
# - app_namespace: Name of the namespace
# - app_name: name of the application
# - app_container_port: port used by the container
# - app_service_protocol: protocol used by the container
# - app_container_source: external or internal image reference to run app from
# - app_volumeMounts (optional): volume mounts on containers
# - app_volumes (optional): volumes to be mounted on containers
# - app_resources (optional): resource limits or requests for containers
# - app_envarguments (optional): environment variables to be used on containers   
# - app_sa_name (optional): service account to be used for the containers

api_version: v1
kind: ConfigMap
metadata:
  name: "{{ item.name }}"
  namespace: "{{ app_namespace }}"
data:
{% for my_item in item.data %}
  {{ my_item.key }}: {{ my_item.value | to_nice_yaml (indent=4) }}
{% endfor %}