# Source: https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles/install_operator

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: "{{ install_operator_namespace }}-og"
  namespace: "{{ install_operator_namespace }}"
{% if install_operator_manage_namespaces | length > 0 %}
spec:
  targetNamespaces: {{ install_operator_manage_namespaces | to_json }}
{% endif %}