---
# vars:

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: "{{ network_name }}"
spec:
  config: |- 
    {
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "{{ network_nic }}",
      "mode": "bridge",
      "ipam": "{{ network_ipam }}"
    }