---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
{% for identity_provider in authentication_authorization_config.identity_providers %}
  - name: "{{ identity_provider.openid_identityprovider_name }}"
    mappingMethod: claim
    type: OpenID
    openID:
      clientID: "{{ identity_provider.openid_client_id }}"
      clientSecret:
        name: "{{ identity_provider.app_secret_name }}"
      extraScopes:
      - email
      - profile
      extraAuthorizeParameters:
        include_granted_scopes: "true"
      claims:
        preferredUsername:
        - preferred_username
        name:
        - name
        email:
        - email
        groups:
        - groups
      issuer: "https://{{ identity_provider.openid_issuer_no_https_prefix }}"
{% endfor %}
