---
# vars:
# - network_name: name of the network, unique in the cluster
# - network_nic: NIC on the worker nodes, e.g. ens224 for the 2nd NIC on VMWare VMs
# - network_ipam: IPAM configuration for the external network.
#   + Static: not shown
#   + Host-local: not shown, only for single host
#   + External DHCP example:
#      {
#        "type": "dhcp"
#      }
#   + Internal whereabouts DHCP example:
#      {
#        "type": "whereabouts",
#        "range": "10.255.246.0/24",
#        "exclude": [
#          "10.255.246.0/25",
#          "10.255.246.128/26"
#        ]
#      }

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: "{{ network_name }}"
spec:
  config: |- 
    {
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "{{ network_nic }}",
      "mode": "bridge",
      "ipam": "{{ network_ipam }}"
    }