---
# vars:
# - app_namespace: Name of the namespace
# - app_name: name of the application
# - app_container_port: port used by the container
# - app_secret_tls_crt: cert file location
# - app_secret_tls_key: cert key file location

api_version: v1
kind: Secret
metadata:
  name: "{{ app_name }}"
  namespace: "{{ app_namespace }}"
type: kubernetes.io/tls
data:
  tls.crt: "{{lookup('ansible.builtin.file', '{{ openshift_example_dir }}/{{ app_secret_tls_crt }}') | b64encode }}"
  tls.key: "{{lookup('ansible.builtin.file', '{{ openshift_example_dir }}/{{ app_secret_tls_key }}') | b64encode }}"