---
ansible_user: Admin
ansible_password: "{{ virtualconnect_admin_password }}"
ansible_connection: local
ansible_network_os: arubanetworks.aos_switch.arubaoss
virtual_connect_shared_uplinks_sets:
- SUS_A
- SUS_B
virtual_connect_shared_uplinks_set_network_suffix:
- -A
- -B
virtual_connect_server_profiles:
- server: RDLHOST01
  connections:
  - 1
  - 2
- server: RDLHOST02
  connections:
  - 1
  - 2
- server: RDLHOST03
  connections:
  - 1
  - 2
- server: RDLHOST04
  connections:
  - 3
  - 4
- server: RDLHOST05
  connections:
  - 3
  - 4